# Generated by Django 3.2.19 on 2023-06-21 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='Super user', max_length=255),
        ),
    ]
